services:
  app:
    container_name: base-frontend_app
    image: base-frontend:0.0.0
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "5008:5173"